/**
 * Testimonial data — CURRENTLY EMPTY. No testimonial, name, company, photo,
 * rating or video has been supplied for this project, and none is invented
 * here. TestimonialSection renders nothing when its filtered list is empty,
 * so every page using it degrades gracefully until real data is added.
 *
 * HOW TO ADD A REAL TESTIMONIAL
 * ------------------------------
 * Written testimonial — push an object into WRITTEN_TESTIMONIALS:
 * {
 *   quote: "Exact client quote, unedited.",
 *   name: "Client full name",
 *   role: "Their job title",
 *   company: "Their company name",
 *   photo: undefined,              // or: import clientPhoto from "../assets/testimonials/jane-doe.jpg"
 *   service: "brand-identity",     // one of the SERVICE slugs below, or "general"
 *   caseStudyLink: "/portfolio/mirror", // optional, only if there's a matching case study
 *   rating: undefined,             // ONLY set this (1-5) if the client gave a genuine rating,
 *                                  // or it came from a verifiable review platform. Leave
 *                                  // undefined otherwise — do not default to 5 stars.
 * }
 *
 * Photos: square, at least 240x240px, JPG or WebP, placed in
 * src/assets/testimonials/ and imported at the top of this file.
 *
 * Video testimonial — push an object into VIDEO_TESTIMONIALS:
 * {
 *   videoSrc: "https://...",       // hosted video URL or an imported local file
 *   poster: undefined,             // imported poster image, required for good UX/CLS
 *   name: "Client full name",
 *   role: "Their job title",
 *   company: "Their company name",
 *   caption: "One-line description of what they talk about",
 *   transcript: "Full plain-text transcript for accessibility.",
 *   service: "website-design",
 * }
 *
 * Video specs: MP4 (H.264), under ~15MB where possible, 16:9, poster image
 * same aspect ratio. Place under src/assets/testimonials/video/.
 */

import type { ServiceSlug } from "./servicesData";
import vicenteVideo from "../assets/testimonials/video/vicente-wedding-notary-testimonial.mp4";
import vicentePoster from "../assets/testimonials/vicente-wedding-notary-poster.jpg";
import djVideo from "../assets/testimonials/video/djremax-koh-samui-testimonial.mp4";
import djPoster from "../assets/testimonials/djremax-koh-samui-poster.jpg";

export interface WrittenTestimonial {
  quote: string;
  name: string;
  role: string;
  company: string;
  photo?: string;
  service: ServiceSlug | "general";
  caseStudyLink?: string;
  /** Only set when a genuine rating exists — never default this. */
  rating?: 1 | 2 | 3 | 4 | 5;
}

export interface VideoTestimonial {
  videoSrc: string;
  poster?: string;
  name: string;
  role: string;
  company: string;
  caption: string;
  /** Plain-text transcript, shown for accessibility and used as caption-track fallback. */
  transcript: string;
  service: ServiceSlug | "general";
}

export const WRITTEN_TESTIMONIALS: WrittenTestimonial[] = [];

/**
 * Both transcripts below were reconstructed from the on-screen captions
 * burned into each source clip (auto-generated by the client's editing
 * app), not from a verbatim audio listen-through — a few connective words
 * are best-effort. Re-check against the original files if exact wording
 * matters, and correct here if anything's off.
 */
export const VIDEO_TESTIMONIALS: VideoTestimonial[] = [
  {
    videoSrc: vicenteVideo,
    poster: vicentePoster,
    name: "Triana Vicente",
    role: "Client",
    company: "Vicente Wedding Notary",
    caption: "On finding OAB Creative and getting her logo designed from scratch.",
    transcript:
      "Hi, my name is Triana Vicente. Shoutout to Amule Emmanuel, OAB Creative — I found him on social media. He is incredible. He helped me from zero. He is very detailed. He gave me the most — my logo for my official new business — and I wanted to share my excellent experience with him. Thank you.",
    service: "brand-identity",
  },
  {
    videoSrc: djVideo,
    poster: djPoster,
    name: "DJ",
    role: "Real Estate Consultant",
    company: "DJRE/MAX Koh Samui",
    caption: "A RE/MAX Island Real Estate consultant on his new DJRE/MAX Koh Samui logo.",
    transcript:
      "My name is DJ, and I'm a real estate consultant here in Koh Samui. What Emmanuel has done has been accurate, totally professional — he's reasonable, and we could really rely on him. He really helped us create a nice logo for us. I really appreciate you, Emmanuel — very, very happy with it. If someone needs a logo, he's your guy. Good luck.",
    service: "brand-identity",
  },
];
